server:
  port: ${SERVER_PORT:8094}

spring:
  application:
    name: rag
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/rag?currentSchema=rag1}
    username: ${DATASOURCE_NAME:rag_user}
    password: ${DATASOURCE_PASSWORD:rag_pass}
    driver-class-name: org.postgresql.Driver
  flyway:
    schemas: rag1
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: codellama:7b
        options:
          temperature: 0.35
          top_p: 0.9
          max_tokens: 2512
          repeat_penalty: 1.1


app:
  rag:
    rabbit:
      exchange: "article.exchange"
      routing-key: "article.outbox"
      queue: "article.outbox.queue"
    embedding :
      embedding-model: ${EMBEDDING_MODEL:EmbeddingsGigaR}
      embedding-url: ${EMBEDDING_URL:https://gigachat.devices.sberbank.ru/api/v1/embeddings}
      secert-token: ${AUTHORIZE_TOKEN:}
      token-url: ${TOKEN_URL:https://ngw.devices.sberbank.ru:9443/api/v2/oauth}